# Ubuntu-based container for discord-image-cleaner
# Uses a lightweight Ubuntu base and installs Python from apt
# Maintainer: generated by GitHub Copilot

FROM ubuntu:24.04

# Python 3.12 is the default in Ubuntu 24.04
ARG DEBIAN_FRONTEND=noninteractive

# Ubuntu 24.04+ may ship with user ubuntu (UID/GID 1000); remove so we can use 1000 for appuser (host volume chown 1000:1000)
RUN userdel -r ubuntu 2>/dev/null || true && \
    groupdel ubuntu 2>/dev/null || true

# install Python and tools
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        python3.12 python3-full python3-pip python3-venv ca-certificates && \
    rm -rf /var/lib/apt/lists/*

# create application directory
WORKDIR /app

# copy requirements early to leverage cache
COPY requirements.txt .

# create virtual environment and install dependencies
RUN python3 -m venv /app/venv && \
    /app/venv/bin/pip install --no-cache-dir -r requirements.txt

# copy source code
COPY . .

# create directories for archive and DB (writable by appuser after chown)
RUN mkdir -p /app/archive /app/data

# non-root user with fixed UID 1000 so host volume ownership can match (chown 1000:1000 archive data)
RUN groupadd --gid 1000 appuser && \
    useradd --uid 1000 --gid 1000 --create-home --shell /bin/bash appuser && \
    chown -R appuser:appuser /app
USER appuser

# Bind-mount ./archive for persistence. Do not VOLUME /app/image_tracker.db:
# Docker mounts volumes as directories, so the app would fail opening a DB "file" there.
VOLUME ["/app/archive"]

# ensure logs are not buffered
ENV PYTHONUNBUFFERED=1

# set PATH to use venv Python
ENV PATH="/app/venv/bin:$PATH"

# default command
CMD ["python3", "bot.py"]
